apiVersion: v1
kind: Service
metadata:
  name: cluster-svc
  labels:
    env: prod
spec:
  selector:
    app: myapp
  type: ClusterIP
  ports:
  - port: 3001 # this can be any port it communicate with all similar pods internally
    targetPort: 80 # this port should match the container port in the pod

---
apiVersion: v1
kind: Service
metadata:
  name: cluster-svc
  labels:
    env: prod
spec:
  selector:
    app: myapp
  type: ClusterIP
  ports:
  - port: 3001 # this can be any port it communicate with all similar pods internally
    targetPort: 80 # this port should match the container port in the pod